default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: kadai6-20_development
test:
  <<: *default
  database: kadai6-20_test
production:
  <<: *default
  database: kadai6-20_production
  username: kadai6-20
  password: <%= ENV['KADAI6-20_DATABASE_PASSWORD'] %>
